[project]
name = "frozendefaultdict"
version = "0.1.1"
description = "Python implementation of a frozen (immutable) default dictionary."
readme = "README.md"
authors = [
    { name = "Adrien Suau", email = "12374487+nelimee@users.noreply.github.com" },
]
requires-python = ">=3.11"
dependencies = ["typing-extensions>=4.0,<5"]

[dependency-groups]
lint = ["ruff==0.16.8", "ty==0.0.82", "mypy>=2,<3", "pydoclint>=0.8,<0.10"]
test = ["pytest>= 9,<10", "pytest-cov>=7,<8"]
dev = [{ include-group = "lint" }, { include-group = "test" }]
all = [
    { include-group = "lint" },
    { include-group = "test" },
    { include-group = "dev" },
]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.mypy]
python_version = "3.11"
files = "src/**/*.py,tests/**/*.py"

[tool.pytest.ini_options]
addopts = "--doctest-modules"

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
tag_format = "v{version}"
commit_parser = "conventional"
allow_zero_version = true
major_on_zero = true
